# Generated by Django 5.1.3 on 2024-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
